/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cafe_Managment_Systems;

//String photopath=null;
//    public ImageIcon resizeImageI(String photopath,byte[] photo){
//        ImageIcon myPhoto=null;
//        if (photopath!=null) {
//            myPhoto=new ImageIcon(photopath);
//        }else{
//            myPhoto=new ImageIcon(photo);
//        }
//            Image img=myPhoto.getImage();
//            Image img1=img.getScaledInstance(label_photo.getWidth(), label_photo.getHeight(), Image.SCALE_SMOOTH);
//            ImageIcon ph=new ImageIcon(img1); 
//            return ph;
//    }
import static java.awt.Color.blue;
import java.util.Calendar;
//import java.util.GregorianCalendar;
//import java.awt.Color;
import java.text.SimpleDateFormat;
//import java.util.Random;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JTextPane;
/**
 *
 * @author 91979
 */
public class Cafe_Managment_System extends javax.swing.JFrame {
    double[]  drink = new double[5];
    double[]  cake = new double[8];
    double[]  cost = new double[3];
    double[] i= new double[13];
    
    /**
     * Creates new form Cafe_Managment_System
     */
    public Cafe_Managment_System() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jChkIceLattle = new javax.swing.JCheckBox();
        jChkEspresso = new javax.swing.JCheckBox();
        jChkCappuccino = new javax.swing.JCheckBox();
        jChkIcedCappuccino = new javax.swing.JCheckBox();
        jScrollPane10 = new javax.swing.JScrollPane();
        jtxtIceLattle = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        jtxtCappuccino = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        jtxtIcedCappuccino = new javax.swing.JTextPane();
        jChkLattle = new javax.swing.JCheckBox();
        jScrollPane19 = new javax.swing.JScrollPane();
        jtxtLattle = new javax.swing.JTextPane();
        jScrollPane20 = new javax.swing.JScrollPane();
        jtxtEspresso = new javax.swing.JTextPane();
        jlblIcedCappuccino = new javax.swing.JLabel();
        jlblIceLattle = new javax.swing.JLabel();
        jlblEspresso = new javax.swing.JLabel();
        jlblCappuccino = new javax.swing.JLabel();
        jlblLattle = new javax.swing.JLabel();
        jlblLattle2 = new javax.swing.JLabel();
        jlblLattle6 = new javax.swing.JLabel();
        jlblLattle7 = new javax.swing.JLabel();
        jlblLattle3 = new javax.swing.JLabel();
        jlblLattle4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jChkCoffee = new javax.swing.JCheckBox();
        jChkRedVelvet = new javax.swing.JCheckBox();
        jChkBoston = new javax.swing.JCheckBox();
        jChkBlack = new javax.swing.JCheckBox();
        jChkLagos = new javax.swing.JCheckBox();
        jChkKilburn = new javax.swing.JCheckBox();
        jChkCarlton = new javax.swing.JCheckBox();
        jChkQueens = new javax.swing.JCheckBox();
        jScrollPane24 = new javax.swing.JScrollPane();
        jtxtQueens = new javax.swing.JTextPane();
        jScrollPane32 = new javax.swing.JScrollPane();
        jtxtKilburn = new javax.swing.JTextPane();
        jScrollPane33 = new javax.swing.JScrollPane();
        jtxtCarlton = new javax.swing.JTextPane();
        jScrollPane34 = new javax.swing.JScrollPane();
        jtxtLagos = new javax.swing.JTextPane();
        jScrollPane35 = new javax.swing.JScrollPane();
        jtxtBlack = new javax.swing.JTextPane();
        jScrollPane36 = new javax.swing.JScrollPane();
        jtxtBoston = new javax.swing.JTextPane();
        jScrollPane37 = new javax.swing.JScrollPane();
        jtxtRedVelvet = new javax.swing.JTextPane();
        jScrollPane39 = new javax.swing.JScrollPane();
        jtxtCoffee = new javax.swing.JTextPane();
        jlblCoffee = new javax.swing.JLabel();
        jlblQueens = new javax.swing.JLabel();
        jlblBoston = new javax.swing.JLabel();
        jlblRedVelVetCake = new javax.swing.JLabel();
        jlblBlack = new javax.swing.JLabel();
        jlblLagos = new javax.swing.JLabel();
        jlblKilburn = new javax.swing.JLabel();
        jlblCarlton = new javax.swing.JLabel();
        jlblLattle8 = new javax.swing.JLabel();
        jlblLattle9 = new javax.swing.JLabel();
        jlblLattle10 = new javax.swing.JLabel();
        jlblLattle11 = new javax.swing.JLabel();
        jlblLattle12 = new javax.swing.JLabel();
        jlblLattle13 = new javax.swing.JLabel();
        jlblLattle14 = new javax.swing.JLabel();
        jlblLattle15 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jlblTaxContent = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();
        jlblSubTotal = new javax.swing.JLabel();
        jlblTax = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlblCostCake = new javax.swing.JLabel();
        jlblCostDrinks = new javax.swing.JLabel();
        jlblService = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jBtnTotal = new javax.swing.JButton();
        jBtnReceipt = new javax.swing.JButton();
        jBtnReset = new javax.swing.JButton();
        jBtnExit = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jlblRemark = new javax.swing.JLabel();
        jlblRemarks = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1368, 730));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("Cafe Managment Systems");

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Webdings", 1, 12)); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\91979\\Documents\\NetBeansProjects\\Cafe_Managment\\src\\Cafe_Managment_Systems\\icons\\cafe_icon3.png")); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\91979\\Documents\\NetBeansProjects\\Cafe_Managment\\src\\Cafe_Managment_Systems\\icons\\cafe-icon2.png")); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\91979\\Documents\\NetBeansProjects\\Cafe_Managment\\src\\Cafe_Managment_Systems\\icons\\cafe_icon3.png")); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\91979\\Documents\\NetBeansProjects\\Cafe_Managment\\src\\Cafe_Managment_Systems\\icons\\cafe_icon1.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)))
                .addGap(20, 20, 20)
                .addComponent(jLabel9))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(jLabel9)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jChkIceLattle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jChkIceLattle.setForeground(new java.awt.Color(0, 102, 255));
        jChkIceLattle.setText("Ice Lattle");
        jChkIceLattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkIceLattleMouseClicked(evt);
            }
        });
        jChkIceLattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkIceLattleActionPerformed(evt);
            }
        });
        jPanel1.add(jChkIceLattle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jChkEspresso.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jChkEspresso.setForeground(new java.awt.Color(0, 102, 255));
        jChkEspresso.setText("Espresso");
        jChkEspresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkEspressoActionPerformed(evt);
            }
        });
        jPanel1.add(jChkEspresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jChkCappuccino.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jChkCappuccino.setForeground(new java.awt.Color(0, 102, 255));
        jChkCappuccino.setText("Cappuccino");
        jChkCappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkCappuccinoActionPerformed(evt);
            }
        });
        jPanel1.add(jChkCappuccino, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        jChkIcedCappuccino.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jChkIcedCappuccino.setForeground(new java.awt.Color(0, 102, 255));
        jChkIcedCappuccino.setText("Iced Cappuccino");
        jChkIcedCappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkIcedCappuccinoActionPerformed(evt);
            }
        });
        jPanel1.add(jChkIcedCappuccino, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        jtxtIceLattle.setBackground(new java.awt.Color(102, 255, 255));
        jtxtIceLattle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        jtxtIceLattle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtIceLattle.setForeground(new java.awt.Color(0, 102, 255));
        jtxtIceLattle.setText("0");
        jtxtIceLattle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtIceLattleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtIceLattleFocusLost(evt);
            }
        });
        jScrollPane10.setViewportView(jtxtIceLattle);

        jPanel1.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 100, 35));

        jtxtCappuccino.setBackground(new java.awt.Color(102, 255, 255));
        jtxtCappuccino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        jtxtCappuccino.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtCappuccino.setForeground(new java.awt.Color(0, 102, 255));
        jtxtCappuccino.setText("0");
        jtxtCappuccino.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtCappuccinoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtCappuccinoFocusLost(evt);
            }
        });
        jScrollPane11.setViewportView(jtxtCappuccino);

        jPanel1.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 100, 35));

        jtxtIcedCappuccino.setBackground(new java.awt.Color(102, 255, 255));
        jtxtIcedCappuccino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        jtxtIcedCappuccino.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtIcedCappuccino.setForeground(new java.awt.Color(0, 102, 255));
        jtxtIcedCappuccino.setText("0");
        jtxtIcedCappuccino.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtIcedCappuccinoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtIcedCappuccinoFocusLost(evt);
            }
        });
        jScrollPane12.setViewportView(jtxtIcedCappuccino);

        jPanel1.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 100, 35));

        jChkLattle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jChkLattle.setForeground(new java.awt.Color(0, 102, 255));
        jChkLattle.setText("Lattle");
        jChkLattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkLattleActionPerformed(evt);
            }
        });
        jPanel1.add(jChkLattle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jtxtLattle.setBackground(new java.awt.Color(102, 255, 255));
        jtxtLattle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        jtxtLattle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtLattle.setForeground(new java.awt.Color(0, 102, 255));
        jtxtLattle.setText("0");
        jtxtLattle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtLattleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtLattleFocusLost(evt);
            }
        });
        jtxtLattle.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jtxtLattleCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jScrollPane19.setViewportView(jtxtLattle);

        jPanel1.add(jScrollPane19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 100, 35));

        jtxtEspresso.setBackground(new java.awt.Color(102, 255, 255));
        jtxtEspresso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        jtxtEspresso.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtEspresso.setForeground(new java.awt.Color(0, 102, 255));
        jtxtEspresso.setText("0");
        jtxtEspresso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtEspressoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtEspressoFocusLost(evt);
            }
        });
        jScrollPane20.setViewportView(jtxtEspresso);

        jPanel1.add(jScrollPane20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 100, 35));

        jlblIcedCappuccino.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlblIcedCappuccino.setForeground(new java.awt.Color(0, 102, 255));
        jlblIcedCappuccino.setText("100");
        jPanel1.add(jlblIcedCappuccino, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 40, 30));

        jlblIceLattle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlblIceLattle.setForeground(new java.awt.Color(0, 102, 255));
        jlblIceLattle.setText("70");
        jPanel1.add(jlblIceLattle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 30, 30));

        jlblEspresso.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlblEspresso.setForeground(new java.awt.Color(0, 102, 255));
        jlblEspresso.setText("80");
        jPanel1.add(jlblEspresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 30, 30));

        jlblCappuccino.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlblCappuccino.setForeground(new java.awt.Color(0, 102, 255));
        jlblCappuccino.setText("100");
        jPanel1.add(jlblCappuccino, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 40, 30));

        jlblLattle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlblLattle.setForeground(new java.awt.Color(0, 102, 255));
        jlblLattle.setText("50 ");
        jPanel1.add(jlblLattle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 40, 30));

        jlblLattle2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlblLattle2.setForeground(new java.awt.Color(0, 102, 255));
        jlblLattle2.setText("₹.");
        jPanel1.add(jlblLattle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 30, 30));

        jlblLattle6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlblLattle6.setForeground(new java.awt.Color(0, 102, 255));
        jlblLattle6.setText("₹.");
        jPanel1.add(jlblLattle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 30, 30));

        jlblLattle7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlblLattle7.setForeground(new java.awt.Color(0, 102, 255));
        jlblLattle7.setText("₹.");
        jPanel1.add(jlblLattle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 30, 30));

        jlblLattle3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlblLattle3.setForeground(new java.awt.Color(0, 102, 255));
        jlblLattle3.setText("₹.");
        jPanel1.add(jlblLattle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 30, 30));

        jlblLattle4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlblLattle4.setForeground(new java.awt.Color(0, 102, 255));
        jlblLattle4.setText("₹.");
        jPanel1.add(jlblLattle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 30, 30));

        jPanel8.setBackground(new java.awt.Color(0, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jChkCoffee.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jChkCoffee.setForeground(new java.awt.Color(0, 102, 255));
        jChkCoffee.setText("Coffee Cake");
        jChkCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkCoffeeActionPerformed(evt);
            }
        });
        jPanel8.add(jChkCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jChkRedVelvet.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jChkRedVelvet.setForeground(new java.awt.Color(0, 102, 255));
        jChkRedVelvet.setText("Red Velvet Cake");
        jChkRedVelvet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkRedVelvetActionPerformed(evt);
            }
        });
        jPanel8.add(jChkRedVelvet, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jChkBoston.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jChkBoston.setForeground(new java.awt.Color(0, 102, 255));
        jChkBoston.setText("Boston Cream Pie");
        jChkBoston.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkBostonActionPerformed(evt);
            }
        });
        jPanel8.add(jChkBoston, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jChkBlack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jChkBlack.setForeground(new java.awt.Color(0, 102, 255));
        jChkBlack.setText("Black Forest Cake");
        jChkBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkBlackActionPerformed(evt);
            }
        });
        jPanel8.add(jChkBlack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jChkLagos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jChkLagos.setForeground(new java.awt.Color(0, 102, 255));
        jChkLagos.setText("Lagos Chocolate Cake");
        jChkLagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkLagosActionPerformed(evt);
            }
        });
        jPanel8.add(jChkLagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jChkKilburn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jChkKilburn.setForeground(new java.awt.Color(0, 102, 255));
        jChkKilburn.setText("Kilburn Chocolate Cake");
        jChkKilburn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkKilburnActionPerformed(evt);
            }
        });
        jPanel8.add(jChkKilburn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jChkCarlton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jChkCarlton.setForeground(new java.awt.Color(0, 102, 255));
        jChkCarlton.setText("Carlton Hill Chocolate Cake");
        jChkCarlton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkCarltonActionPerformed(evt);
            }
        });
        jPanel8.add(jChkCarlton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jChkQueens.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jChkQueens.setForeground(new java.awt.Color(0, 102, 255));
        jChkQueens.setText("Queen's Park Chocolate Cake");
        jChkQueens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkQueensActionPerformed(evt);
            }
        });
        jPanel8.add(jChkQueens, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, 31));

        jtxtQueens.setBackground(new java.awt.Color(102, 255, 255));
        jtxtQueens.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        jtxtQueens.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jtxtQueens.setForeground(new java.awt.Color(0, 102, 255));
        jtxtQueens.setText("0");
        jtxtQueens.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtQueensFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtQueensFocusLost(evt);
            }
        });
        jScrollPane24.setViewportView(jtxtQueens);

        jPanel8.add(jScrollPane24, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 331, 80, 30));

        jtxtKilburn.setBackground(new java.awt.Color(102, 255, 255));
        jtxtKilburn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        jtxtKilburn.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jtxtKilburn.setForeground(new java.awt.Color(0, 102, 255));
        jtxtKilburn.setText("0");
        jtxtKilburn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtKilburnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtKilburnFocusLost(evt);
            }
        });
        jScrollPane32.setViewportView(jtxtKilburn);

        jPanel8.add(jScrollPane32, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 80, 31));

        jtxtCarlton.setBackground(new java.awt.Color(102, 255, 255));
        jtxtCarlton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        jtxtCarlton.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jtxtCarlton.setForeground(new java.awt.Color(0, 102, 255));
        jtxtCarlton.setText("0");
        jtxtCarlton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtCarltonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtCarltonFocusLost(evt);
            }
        });
        jScrollPane33.setViewportView(jtxtCarlton);

        jPanel8.add(jScrollPane33, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 80, 31));

        jtxtLagos.setBackground(new java.awt.Color(102, 255, 255));
        jtxtLagos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        jtxtLagos.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jtxtLagos.setForeground(new java.awt.Color(0, 102, 255));
        jtxtLagos.setText("0");
        jtxtLagos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtLagosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtLagosFocusLost(evt);
            }
        });
        jScrollPane34.setViewportView(jtxtLagos);

        jPanel8.add(jScrollPane34, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 80, 31));

        jtxtBlack.setBackground(new java.awt.Color(102, 255, 255));
        jtxtBlack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        jtxtBlack.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jtxtBlack.setForeground(new java.awt.Color(0, 102, 255));
        jtxtBlack.setText("0");
        jtxtBlack.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtBlackFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtBlackFocusLost(evt);
            }
        });
        jScrollPane35.setViewportView(jtxtBlack);

        jPanel8.add(jScrollPane35, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 80, 31));

        jtxtBoston.setBackground(new java.awt.Color(102, 255, 255));
        jtxtBoston.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        jtxtBoston.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jtxtBoston.setForeground(new java.awt.Color(0, 102, 255));
        jtxtBoston.setText("0");
        jtxtBoston.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtBostonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtBostonFocusLost(evt);
            }
        });
        jScrollPane36.setViewportView(jtxtBoston);

        jPanel8.add(jScrollPane36, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 80, 31));

        jtxtRedVelvet.setBackground(new java.awt.Color(102, 255, 255));
        jtxtRedVelvet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        jtxtRedVelvet.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jtxtRedVelvet.setForeground(new java.awt.Color(0, 102, 255));
        jtxtRedVelvet.setText("0");
        jtxtRedVelvet.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtRedVelvetFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtRedVelvetFocusLost(evt);
            }
        });
        jScrollPane37.setViewportView(jtxtRedVelvet);

        jPanel8.add(jScrollPane37, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 80, 31));

        jtxtCoffee.setBackground(new java.awt.Color(102, 255, 255));
        jtxtCoffee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        jtxtCoffee.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jtxtCoffee.setForeground(new java.awt.Color(0, 102, 255));
        jtxtCoffee.setText("0");
        jtxtCoffee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtCoffeeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtCoffeeFocusLost(evt);
            }
        });
        jScrollPane39.setViewportView(jtxtCoffee);

        jPanel8.add(jScrollPane39, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 80, 30));

        jlblCoffee.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlblCoffee.setForeground(new java.awt.Color(0, 102, 255));
        jlblCoffee.setText("50 ");
        jPanel8.add(jlblCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 20, 20));

        jlblQueens.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlblQueens.setForeground(new java.awt.Color(0, 102, 255));
        jlblQueens.setText("250");
        jPanel8.add(jlblQueens, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 30, 30));

        jlblBoston.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlblBoston.setForeground(new java.awt.Color(0, 102, 255));
        jlblBoston.setText("100");
        jPanel8.add(jlblBoston, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 50, 20));

        jlblRedVelVetCake.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlblRedVelVetCake.setForeground(new java.awt.Color(0, 102, 255));
        jlblRedVelVetCake.setText("140 ");
        jPanel8.add(jlblRedVelVetCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 30, 20));

        jlblBlack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlblBlack.setForeground(new java.awt.Color(0, 102, 255));
        jlblBlack.setText("140");
        jPanel8.add(jlblBlack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 30, 20));

        jlblLagos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlblLagos.setForeground(new java.awt.Color(0, 102, 255));
        jlblLagos.setText("140 ");
        jPanel8.add(jlblLagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 30, 20));

        jlblKilburn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlblKilburn.setForeground(new java.awt.Color(0, 102, 255));
        jlblKilburn.setText("150");
        jPanel8.add(jlblKilburn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 30, 20));

        jlblCarlton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlblCarlton.setForeground(new java.awt.Color(0, 102, 255));
        jlblCarlton.setText("160");
        jPanel8.add(jlblCarlton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 30, 20));

        jlblLattle8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlblLattle8.setForeground(new java.awt.Color(0, 102, 255));
        jlblLattle8.setText("₹.");
        jPanel8.add(jlblLattle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 30, 30));

        jlblLattle9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlblLattle9.setForeground(new java.awt.Color(0, 102, 255));
        jlblLattle9.setText("₹.");
        jPanel8.add(jlblLattle9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 20, 20));

        jlblLattle10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlblLattle10.setForeground(new java.awt.Color(0, 102, 255));
        jlblLattle10.setText("₹.");
        jPanel8.add(jlblLattle10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 30, 20));

        jlblLattle11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlblLattle11.setForeground(new java.awt.Color(0, 102, 255));
        jlblLattle11.setText("₹.");
        jPanel8.add(jlblLattle11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 30, 20));

        jlblLattle12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlblLattle12.setForeground(new java.awt.Color(0, 102, 255));
        jlblLattle12.setText("₹.");
        jPanel8.add(jlblLattle12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 30, 20));

        jlblLattle13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlblLattle13.setForeground(new java.awt.Color(0, 102, 255));
        jlblLattle13.setText("₹.");
        jPanel8.add(jlblLattle13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 30, 20));

        jlblLattle14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlblLattle14.setForeground(new java.awt.Color(0, 102, 255));
        jlblLattle14.setText("₹.");
        jPanel8.add(jlblLattle14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 30, 20));

        jlblLattle15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlblLattle15.setForeground(new java.awt.Color(0, 102, 255));
        jlblLattle15.setText("₹.");
        jPanel8.add(jlblLattle15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 30, 20));

        jPanel10.setBackground(new java.awt.Color(0, 204, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jtxtReceipt.setBackground(new java.awt.Color(204, 255, 255));
        jtxtReceipt.setColumns(20);
        jtxtReceipt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jtxtReceipt.setRows(5);
        jtxtReceipt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 255), 2));
        jScrollPane1.setViewportView(jtxtReceipt);

        jLabel14.setFont(new java.awt.Font("Vijaya", 1, 40)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Receipt for purchesed products");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255), 4));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(0, 204, 204));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jlblTaxContent.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlblTaxContent.setForeground(new java.awt.Color(0, 102, 255));
        jlblTaxContent.setText("Tax");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 255));
        jLabel12.setText("Sub Total");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 255));
        jLabel13.setText("Total");

        jlblTotal.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jlblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTotal.setText("0");
        jlblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jlblTotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jlblSubTotal.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jlblSubTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblSubTotal.setText("0");
        jlblSubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jlblSubTotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jlblTax.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jlblTax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTax.setText("0");
        jlblTax.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jlblTax.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlblTax.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jlblTaxContent))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jlblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jlblTaxContent)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        jPanel6.setBackground(new java.awt.Color(0, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("Cost of Drinks");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("Cost of Cakes");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("Service Charge");

        jlblCostCake.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jlblCostCake.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCostCake.setText("0");
        jlblCostCake.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jlblCostCake.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jlblCostDrinks.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jlblCostDrinks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCostDrinks.setText("0");
        jlblCostDrinks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jlblCostDrinks.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jlblService.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jlblService.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblService.setText("2.50");
        jlblService.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jlblService.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblCostCake, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblCostDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jlblService, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlblCostDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCostCake, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jlblService, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnTotal.setBackground(new java.awt.Color(204, 204, 204));
        jBtnTotal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtnTotal.setText("Total");
        jBtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTotalActionPerformed(evt);
            }
        });
        jPanel7.add(jBtnTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jBtnReceipt.setBackground(new java.awt.Color(204, 204, 204));
        jBtnReceipt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtnReceipt.setText("Receipt");
        jBtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReceiptActionPerformed(evt);
            }
        });
        jPanel7.add(jBtnReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jBtnReset.setBackground(new java.awt.Color(204, 204, 204));
        jBtnReset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtnReset.setText("Reset");
        jBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetActionPerformed(evt);
            }
        });
        jPanel7.add(jBtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jBtnExit.setBackground(new java.awt.Color(204, 204, 204));
        jBtnExit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtnExit.setText("Exit");
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });
        jPanel7.add(jBtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblRemark.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlblRemark.setForeground(new java.awt.Color(0, 102, 255));
        jlblRemark.setText("REMARKS: ");
        jPanel5.add(jlblRemark, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 20));

        jlblRemarks.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jlblRemarks.setForeground(new java.awt.Color(255, 0, 0));
        jPanel5.add(jlblRemarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 270, 20));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 380, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 1320, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtnExitActionPerformed

    private void jBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetActionPerformed
        jlblRemarks.setText("");
        jlblTax.setText("0");
        jlblSubTotal.setText("0");
        jlblTotal.setText("0");
        jlblCostDrinks.setText("0");
        jlblCostCake.setText("0");
        jtxtBlack.setText("0");
        jtxtLagos.setText("0");
        jtxtKilburn.setText("0");
        jtxtCarlton.setText("0");
        jtxtQueens.setText("0");
        jtxtRedVelvet.setText("0");
        jtxtBoston.setText("0");
        jtxtCoffee.setText("0");
        jtxtLattle.setText("0");
        jtxtIceLattle.setText("0");
        jtxtEspresso.setText("0");
        jtxtCappuccino.setText("0");
        jtxtIcedCappuccino.setText("0");
        jChkLattle.setSelected(false);
        jChkIceLattle.setSelected(false);
        jChkEspresso.setSelected(false);
        jChkCappuccino.setSelected(false);
        jChkIcedCappuccino.setSelected(false);
        jChkCoffee.setSelected(false);
        jChkRedVelvet.setSelected(false);
        jChkBoston.setSelected(false);
        jChkBlack.setSelected(false);
        jChkLagos.setSelected(false);
        jChkKilburn.setSelected(false);
        jChkCarlton.setSelected(false);
        jChkQueens.setSelected(false);
        jtxtReceipt.setText(null);
    }//GEN-LAST:event_jBtnResetActionPerformed

    private void jBtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReceiptActionPerformed
        if((!jlblCostDrinks.getText().equals("0")&&!jlblCostDrinks.getText().equals("0.00"))
                ||(!jlblCostCake.getText().equals("0")&& !jlblCostCake.getText().equals("0.00"))){
        drink[0]=Double.parseDouble(jtxtLattle.getText());
        drink[1]=Double.parseDouble(jtxtIceLattle.getText());
        drink[2]=Double.parseDouble(jtxtEspresso.getText());
        drink[3]=Double.parseDouble(jtxtCappuccino.getText());
        drink[4]=Double.parseDouble(jtxtIcedCappuccino.getText());
        cake[0]=Double.parseDouble(jtxtCoffee.getText());
        cake[1]=Double.parseDouble(jtxtRedVelvet.getText());
        cake[2]=Double.parseDouble(jtxtBoston.getText());
        cake[3]=Double.parseDouble(jtxtBlack.getText());
        // parsing the count of user needs.
        cake[4]=Double.parseDouble(jtxtLagos.getText());
        cake[5]=Double.parseDouble(jtxtKilburn.getText());
        cake[6]=Double.parseDouble(jtxtCarlton.getText());
        cake[7]=Double.parseDouble(jtxtQueens.getText());
        // Cost Total
        cost[0]=Double.parseDouble(jlblTax.getText());
        cost[1]=Double.parseDouble(jlblSubTotal.getText());
        cost[2]=Double.parseDouble(jlblTotal.getText());
        //Reference Number Code:
        int ref=1325+(int)(Math.random()*4238);
        // Date Code:
        Calendar timer=Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime=new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat tDate=new SimpleDateFormat("dd-MM-yyyy");
        tDate.format(timer.getTime());
        jtxtReceipt.append(
            "\tCafe Management Systems:\n" +
            "Reference:\t\t\t"+ref+
            "\n=========================================");
        // Appending all Details in Receipt 
        jtxtReceipt.append("\nLattle:\t\t\t"+drink[0] +
            "\nIce Lattle:\t\t\t"+drink[1]+
            "\nEsPresso:\t\t\t"+drink[2]+
            "\nCappuccino:\t\t\t"+drink[3]+
            "\nIced Cappuccino:\t\t"+drink[4]+
            "\n========================================="+
            "\nCofee:\t\t\t"+cake[0]+
            "\nRed Velvet Cakes:\t\t"+cake[1]+
            "\nBoston Cream Pie:\t\t"+cake[2]+
            "\nBlack Forest Cake:\t\t"+cake[3]+
            "\nLagos Choclate Cake:\t\t"+cake[4]+
            "\nKilburn Choclate Cake:\t\t"+cake[5]+
            "\nCarlton Hill Chocolate Cake:\t\t"+cake[6]+
            "\nQueen's Park Chocolate Cake:\t\t"+cake[7]+
            "\n========================================="+ 
            "\nTax:\t\t\t" + cost[0]+
            "\nSubTotal:\t\t\t" + cost[1]+
            "\nTotal:\t\t\t" + cost[2]+        
            "\n========================================="+
            // Date Appending in Receipt
            "\n\nDate:"+tDate.format(timer.getTime())+
            "\tTime: "+tTime.format(timer.getTime())+        
            "\n\tThank You\n"+
            "=========================================\n");
        }
    }//GEN-LAST:event_jBtnReceiptActionPerformed

    private void jBtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTotalActionPerformed
        if((!jlblCostDrinks.getText().equals("0")&&!jlblCostDrinks.getText().equals("0.00"))
                ||(!jlblCostCake.getText().equals("0")&& !jlblCostCake.getText().equals("0.00"))){
        double costOfDrink=Double.parseDouble(jlblCostDrinks.getText());
        double costOfCake=Double.parseDouble(jlblCostCake.getText());
        double costOfService=Double.parseDouble(jlblService.getText());
        double sum=costOfDrink+costOfCake+costOfService;
        double tax=3.9;
        double cTax=(sum*tax)/100;
        String ttax=String.format("%.2f", cTax);
        jlblTax.setText(ttax);
        String subSum=String.format("%.2f", sum);
        jlblSubTotal.setText(subSum);
        double totalSubTax=cTax+sum;
        String total=String.format("%.2f", totalSubTax);
        jlblTotal.setText(total);
        }
        
    }//GEN-LAST:event_jBtnTotalActionPerformed

    private void jChkQueensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkQueensActionPerformed
    polymorphismMethod(jlblCostCake,jtxtQueens,jlblQueens,jChkQueens,12);
    }//GEN-LAST:event_jChkQueensActionPerformed

    private void jChkCarltonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkCarltonActionPerformed
    polymorphismMethod(jlblCostCake,jtxtCarlton,jlblCarlton,jChkCarlton,11);
    }//GEN-LAST:event_jChkCarltonActionPerformed

    private void jChkKilburnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkKilburnActionPerformed
    polymorphismMethod(jlblCostCake,jtxtKilburn,jlblKilburn,jChkKilburn,10);
    }//GEN-LAST:event_jChkKilburnActionPerformed

    private void jChkLagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkLagosActionPerformed
    polymorphismMethod(jlblCostCake,jtxtLagos,jlblLagos,jChkLagos,9);
    }//GEN-LAST:event_jChkLagosActionPerformed

    private void jChkBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkBlackActionPerformed
    polymorphismMethod(jlblCostCake,jtxtBlack,jlblBlack,jChkBlack,8);
    }//GEN-LAST:event_jChkBlackActionPerformed

    private void jChkBostonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkBostonActionPerformed
    polymorphismMethod(jlblCostCake,jtxtBoston,jlblBoston,jChkBoston,6);
    }//GEN-LAST:event_jChkBostonActionPerformed
    private void polymorphismMethod(JLabel whichType, JTextPane pcount,JLabel pcost,JCheckBox select,int position){
            if(select.isSelected())
            {
                double total=Double.parseDouble(whichType.getText());
                double count=Double.parseDouble(pcount.getText());
                double cost=Double.parseDouble(pcost.getText());
                i[position]= (count * cost)+total;
                String pDrink=String.format("%.2f", i[position]);
                whichType.setText(pDrink);
            }
}
    
    private void jChkRedVelvetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkRedVelvetActionPerformed
    polymorphismMethod(jlblCostCake,jtxtRedVelvet,jlblRedVelVetCake,jChkRedVelvet,7);
    }//GEN-LAST:event_jChkRedVelvetActionPerformed

    private void jChkCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkCoffeeActionPerformed
    polymorphismMethod(jlblCostCake,jtxtCoffee,jlblCoffee,jChkCoffee,5);       
    }//GEN-LAST:event_jChkCoffeeActionPerformed

    private void jtxtLattleCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jtxtLattleCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLattleCaretPositionChanged

    private void jChkLattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkLattleActionPerformed
    polymorphismMethod(jlblCostDrinks,jtxtLattle,jlblLattle,jChkLattle,0);    
    }//GEN-LAST:event_jChkLattleActionPerformed

    private void jChkIcedCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkIcedCappuccinoActionPerformed
    polymorphismMethod(jlblCostDrinks,jtxtIcedCappuccino,jlblIcedCappuccino,jChkIcedCappuccino,4);
    }//GEN-LAST:event_jChkIcedCappuccinoActionPerformed

    private void jChkCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkCappuccinoActionPerformed
    polymorphismMethod(jlblCostDrinks,jtxtCappuccino,jlblCappuccino,jChkCappuccino,3);
    }//GEN-LAST:event_jChkCappuccinoActionPerformed

    private void jChkEspressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkEspressoActionPerformed
    polymorphismMethod(jlblCostDrinks,jtxtEspresso,jlblEspresso,jChkEspresso,2);
    }//GEN-LAST:event_jChkEspressoActionPerformed

    private void jChkIceLattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkIceLattleActionPerformed
    polymorphismMethod(jlblCostDrinks,jtxtIceLattle,jlblIceLattle,jChkIceLattle,1);    
    }//GEN-LAST:event_jChkIceLattleActionPerformed

    private void jChkIceLattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkIceLattleMouseClicked

    }//GEN-LAST:event_jChkIceLattleMouseClicked
  
  private  void holderChangeOn(JTextPane txt){
      if(txt.getText().equals("0")){
           txt.setText("");
           txt.setForeground(blue);
           
       }
  }
  
  private static boolean numCheck(JTextPane txt){
      String s = txt.getText();
      for(int i=0;i<s.length();i++){
          if('0'<=s.charAt(i)&&s.charAt(i)<='9'){
              
          }else{
              return false;
          }
      }
      return true;
  }
   private  void holderChangeOff(JTextPane txt){
      if(txt.getText().equals("")){
           txt.setText("0");
           txt.setForeground(blue);
       }
      else if(!txt.getText().equals("0")||!txt.getText().equals(""))
      {
          if(numCheck(txt)==true){
               jlblRemarks.setText("");
           }else{
              jlblRemarks.setText("Please enter numbers");
              txt.setText("0");
              txt.setForeground(blue);
          }
      }
  }
  
    private void jtxtLattleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtLattleFocusGained
        holderChangeOn(jtxtLattle);
    }//GEN-LAST:event_jtxtLattleFocusGained

    private void jtxtLattleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtLattleFocusLost
        holderChangeOff(jtxtLattle);
    }//GEN-LAST:event_jtxtLattleFocusLost

    private void jtxtIceLattleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtIceLattleFocusGained
      holderChangeOn(jtxtIceLattle);
    }//GEN-LAST:event_jtxtIceLattleFocusGained

    private void jtxtIceLattleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtIceLattleFocusLost
        holderChangeOff(jtxtIceLattle);
    }//GEN-LAST:event_jtxtIceLattleFocusLost

    private void jtxtEspressoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtEspressoFocusGained
        holderChangeOn(jtxtEspresso);
    }//GEN-LAST:event_jtxtEspressoFocusGained

    private void jtxtEspressoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtEspressoFocusLost
      holderChangeOff(jtxtEspresso);
    }//GEN-LAST:event_jtxtEspressoFocusLost

    private void jtxtCappuccinoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtCappuccinoFocusGained
        holderChangeOn(jtxtCappuccino);
    }//GEN-LAST:event_jtxtCappuccinoFocusGained

    private void jtxtCappuccinoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtCappuccinoFocusLost
        holderChangeOff(jtxtCappuccino);
    }//GEN-LAST:event_jtxtCappuccinoFocusLost

    private void jtxtIcedCappuccinoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtIcedCappuccinoFocusGained
        holderChangeOn(jtxtIcedCappuccino);
    }//GEN-LAST:event_jtxtIcedCappuccinoFocusGained

    private void jtxtIcedCappuccinoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtIcedCappuccinoFocusLost
       holderChangeOff(jtxtIcedCappuccino);
    }//GEN-LAST:event_jtxtIcedCappuccinoFocusLost

    private void jtxtCoffeeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtCoffeeFocusGained
      holderChangeOn(jtxtCoffee);
    }//GEN-LAST:event_jtxtCoffeeFocusGained

    private void jtxtCoffeeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtCoffeeFocusLost
       holderChangeOff(jtxtCoffee);
    }//GEN-LAST:event_jtxtCoffeeFocusLost

    private void jtxtBostonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtBostonFocusGained
      holderChangeOn(jtxtBoston);
    }//GEN-LAST:event_jtxtBostonFocusGained

    private void jtxtBostonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtBostonFocusLost
      holderChangeOff(jtxtBoston);
    }//GEN-LAST:event_jtxtBostonFocusLost

    private void jtxtRedVelvetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtRedVelvetFocusGained
       holderChangeOn(jtxtRedVelvet);
    }//GEN-LAST:event_jtxtRedVelvetFocusGained

    private void jtxtRedVelvetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtRedVelvetFocusLost
        holderChangeOff(jtxtRedVelvet);
    }//GEN-LAST:event_jtxtRedVelvetFocusLost

    private void jtxtBlackFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtBlackFocusGained
      holderChangeOn(jtxtBlack);
    }//GEN-LAST:event_jtxtBlackFocusGained

    private void jtxtBlackFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtBlackFocusLost
      holderChangeOff(jtxtBlack);
    }//GEN-LAST:event_jtxtBlackFocusLost

    private void jtxtLagosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtLagosFocusGained
      holderChangeOn(jtxtLagos);
    }//GEN-LAST:event_jtxtLagosFocusGained

    private void jtxtLagosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtLagosFocusLost
      holderChangeOff(jtxtLagos);
    }//GEN-LAST:event_jtxtLagosFocusLost

    private void jtxtKilburnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtKilburnFocusGained
        holderChangeOn(jtxtKilburn);
    }//GEN-LAST:event_jtxtKilburnFocusGained

    private void jtxtKilburnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtKilburnFocusLost
       holderChangeOff(jtxtKilburn);
    }//GEN-LAST:event_jtxtKilburnFocusLost

    private void jtxtCarltonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtCarltonFocusGained
      holderChangeOn(jtxtCarlton);
    }//GEN-LAST:event_jtxtCarltonFocusGained

    private void jtxtCarltonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtCarltonFocusLost
      holderChangeOff(jtxtCarlton);
    }//GEN-LAST:event_jtxtCarltonFocusLost

    private void jtxtQueensFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtQueensFocusGained
       holderChangeOn(jtxtQueens); 
    }//GEN-LAST:event_jtxtQueensFocusGained

    private void jtxtQueensFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtQueensFocusLost
       holderChangeOff(jtxtQueens);
    }//GEN-LAST:event_jtxtQueensFocusLost
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cafe_Managment_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cafe_Managment_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cafe_Managment_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cafe_Managment_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cafe_Managment_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnReceipt;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JButton jBtnTotal;
    private javax.swing.JCheckBox jChkBlack;
    private javax.swing.JCheckBox jChkBoston;
    private javax.swing.JCheckBox jChkCappuccino;
    private javax.swing.JCheckBox jChkCarlton;
    private javax.swing.JCheckBox jChkCoffee;
    private javax.swing.JCheckBox jChkEspresso;
    private javax.swing.JCheckBox jChkIceLattle;
    private javax.swing.JCheckBox jChkIcedCappuccino;
    private javax.swing.JCheckBox jChkKilburn;
    private javax.swing.JCheckBox jChkLagos;
    private javax.swing.JCheckBox jChkLattle;
    private javax.swing.JCheckBox jChkQueens;
    private javax.swing.JCheckBox jChkRedVelvet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JScrollPane jScrollPane33;
    private javax.swing.JScrollPane jScrollPane34;
    private javax.swing.JScrollPane jScrollPane35;
    private javax.swing.JScrollPane jScrollPane36;
    private javax.swing.JScrollPane jScrollPane37;
    private javax.swing.JScrollPane jScrollPane39;
    private javax.swing.JLabel jlblBlack;
    private javax.swing.JLabel jlblBoston;
    private javax.swing.JLabel jlblCappuccino;
    private javax.swing.JLabel jlblCarlton;
    private javax.swing.JLabel jlblCoffee;
    private javax.swing.JLabel jlblCostCake;
    private javax.swing.JLabel jlblCostDrinks;
    private javax.swing.JLabel jlblEspresso;
    private javax.swing.JLabel jlblIceLattle;
    private javax.swing.JLabel jlblIcedCappuccino;
    private javax.swing.JLabel jlblKilburn;
    private javax.swing.JLabel jlblLagos;
    private javax.swing.JLabel jlblLattle;
    private javax.swing.JLabel jlblLattle10;
    private javax.swing.JLabel jlblLattle11;
    private javax.swing.JLabel jlblLattle12;
    private javax.swing.JLabel jlblLattle13;
    private javax.swing.JLabel jlblLattle14;
    private javax.swing.JLabel jlblLattle15;
    private javax.swing.JLabel jlblLattle2;
    private javax.swing.JLabel jlblLattle3;
    private javax.swing.JLabel jlblLattle4;
    private javax.swing.JLabel jlblLattle6;
    private javax.swing.JLabel jlblLattle7;
    private javax.swing.JLabel jlblLattle8;
    private javax.swing.JLabel jlblLattle9;
    private javax.swing.JLabel jlblQueens;
    private javax.swing.JLabel jlblRedVelVetCake;
    private javax.swing.JLabel jlblRemark;
    private javax.swing.JLabel jlblRemarks;
    private javax.swing.JLabel jlblService;
    private javax.swing.JLabel jlblSubTotal;
    private javax.swing.JLabel jlblTax;
    private javax.swing.JLabel jlblTaxContent;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JTextPane jtxtBlack;
    private javax.swing.JTextPane jtxtBoston;
    private javax.swing.JTextPane jtxtCappuccino;
    private javax.swing.JTextPane jtxtCarlton;
    private javax.swing.JTextPane jtxtCoffee;
    private javax.swing.JTextPane jtxtEspresso;
    private javax.swing.JTextPane jtxtIceLattle;
    private javax.swing.JTextPane jtxtIcedCappuccino;
    private javax.swing.JTextPane jtxtKilburn;
    private javax.swing.JTextPane jtxtLagos;
    private javax.swing.JTextPane jtxtLattle;
    private javax.swing.JTextPane jtxtQueens;
    private javax.swing.JTextArea jtxtReceipt;
    private javax.swing.JTextPane jtxtRedVelvet;
    // End of variables declaration//GEN-END:variables
}
